//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.BuiltinInterfaces;

namespace RosMessageTypes.Assets
{
    [Serializable]
    public class OmniJointStateMsg : Message
    {
        public const string k_RosMessageName = "Assets/OmniJointState";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public uint seq;
        public TimeMsg stamp;
        public string frame_id;
        public string[] name;
        public double[] position;
        public double[] velocity;
        public double[] effort;

        public OmniJointStateMsg()
        {
            this.header = new Std.HeaderMsg();
            this.seq = 0;
            this.stamp = new TimeMsg();
            this.frame_id = "";
            this.name = new string[0];
            this.position = new double[0];
            this.velocity = new double[0];
            this.effort = new double[0];
        }

        public OmniJointStateMsg(Std.HeaderMsg header, uint seq, TimeMsg stamp, string frame_id, string[] name, double[] position, double[] velocity, double[] effort)
        {
            this.header = header;
            this.seq = seq;
            this.stamp = stamp;
            this.frame_id = frame_id;
            this.name = name;
            this.position = position;
            this.velocity = velocity;
            this.effort = effort;
        }

        public static OmniJointStateMsg Deserialize(MessageDeserializer deserializer) => new OmniJointStateMsg(deserializer);

        private OmniJointStateMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.seq);
            this.stamp = TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.frame_id);
            deserializer.Read(out this.name, deserializer.ReadLength());
            deserializer.Read(out this.position, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.velocity, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.effort, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.seq);
            serializer.Write(this.stamp);
            serializer.Write(this.frame_id);
            serializer.WriteLength(this.name);
            serializer.Write(this.name);
            serializer.WriteLength(this.position);
            serializer.Write(this.position);
            serializer.WriteLength(this.velocity);
            serializer.Write(this.velocity);
            serializer.WriteLength(this.effort);
            serializer.Write(this.effort);
        }

        public override string ToString()
        {
            return "OmniJointStateMsg: " +
            "\nheader: " + header.ToString() +
            "\nseq: " + seq.ToString() +
            "\nstamp: " + stamp.ToString() +
            "\nframe_id: " + frame_id.ToString() +
            "\nname: " + System.String.Join(", ", name.ToList()) +
            "\nposition: " + System.String.Join(", ", position.ToList()) +
            "\nvelocity: " + System.String.Join(", ", velocity.ToList()) +
            "\neffort: " + System.String.Join(", ", effort.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
